version: '3.4'

services:
  psql-db:
    image: postgres:12
    ports:
      - '5431:5432'
    environment:
      - POSTGRES_USER=nest
      - POSTGRES_PASSWORD=nest
      - POSTGRES_DB=nest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ws-network

volumes:
  postgres_data:

networks:
  ws-network: